
PREFIX=/opt/nma
CXX = g++
STRIP = strip
MAKE = make
AR = ar ruv
RANLIB = ranlib

ACE_include=$(ACE_ROOT)
ACE_lib=$(ACE_ROOT)/lib

BOOST_include=/usr/include/boost
BOOST_lib=/usr/local/lib

PCAP_include=/usr/include/pcap
PCAP_lib=/usr/local/lib

PGSQL_include=/usr/local/include
PGSQL_lib=/usr/local

LIBXML2_include=/usr/local/include/libxml2
LIBXML2_lib=/usr/local/lib

berkeleyDB_include=/usr/local/berkeleydb/include
berkeleyDB_lib=/usr/local/berkeleydb/lib
